[default.extend-words]
Lazer = "Lazer"
bck = "bck"
nd = "nd"
ue = "ue"
thr = "thr"
lod = "lod"
LOD = "LOD"
metalness = "metalness"

[files]
extend-exclude = [
    "app/emoji/**", 
    "config/credentials.yml.enc", 
    "config/locales/**", 
    "coverage/**", 
    "test/**", 
    "*.sql",
    "vendor/**",
    "node_modules/**",
    "tmp/**",
    "log/**",
    "storage/**",
    "**/gems/**",
    "app/client-ai-models**"
]