smol = true
telemetry = false
[install]
exact = true
saveTextLockfile = false
[run]
bun = true
[install.cache]
disable = true
disableManifest = true
[install.security]
scanner = "@socketsecurity/bun-security-scanner"